### PR TITLE
graphdb repository migrations

### PR DESCRIPTION
**Pull request by C-Loftus**
Adds the necessary migrations for graphdb to have the repositories added on startup. Images here show a successful run for the hu02 assets

Just wanted to confirm that these config settings are reasonable. Wasn't sure if there are specific other settings we need or you added in the GUI. I am using a default example config. 

image
image
image
image

### CODE REVIEW

**Review by webb-ben — APPROVED** [review]

**Comment by adplincinst** [comment]
A few thoughts... Good to see the provisioning of iow and iow-prov managed as (.ttl) artifacts. However, I also constructed my own for testing purposes with nabu so it begs the question where should database provisioning artifacts live (in one place). Does it belong in scheduler or nabu or independent of either?  I think for now we just need to manage the sources of truth for the graph repo provisioning with is a good thing.  Also I think the configuration item 'disable-SameAs' *might* be problematic as we depend on  owl:sameAs inferencing capabilities when linking two graph objects created independently (different source) thought to refer to the same physical thing.  What happens when you run  query `?s owl:sameAs  ?p` on the graph do we have any triples that match this?

**Comment by C-Loftus** [comment]
> where should database provisioning artifacts live 

I can speak to this first point I think. I feel it makes sense to me to have configuration for architecture be next to the code that spins it up. So in this case, the ttl files for graphdb can be in this repo assuming we are using the docker compose here to spin it up. Unless I am misunderstanding and you are running the migrations in a different way than I am.

**Comment by adplincinst** [comment]
@C-Loftus  I am thinking how we can use a graphdb configuration .ttl from both scheduler (for provisioning enviornments) and for standalone nabu for testing given that it ultimately interacts with graphdb directly (and scheduler indirectly via nabu).  Also we should consider that graphdb provisioning & updates are not always in concert with scheduler. Is it possible to manage the runtime management of graphdb and its geoconnex repositories independent from scheduler such that it can be used by scheduler and/or nabut standalone?

**Comment by C-Loftus** [comment]
I think until we have a better idea of graphdb versioning and deployment it may make sense to keep here.  

And if I recall, can't nabu source a remote config file? So for testing we can source the raw config from this repo. 

But I agree that in the future we could have a separate container / repo just for graphdb management. Just trying to keep iterations fast for time being

**Comment by C-Loftus** [comment]
Going to merge this into our `cleanerBuild` dev branch since it helps make local dev easier to iterate on. This isn't permanent obviously, just makes dev quicker. We can change the config again going forward.

**Pull request merged**
